### ISSUE TITLE
Testes de todos - Erro no Primeiro teste?

### ISSUE THREAD

**Issue by rogeriop1990cv** [rocketseat-education/ignite-template-conceitos-do-nodejs#8]
O enunciado do teste é esse.
* **Should be able to list all user's todos**

Me fez acredita que só criando a rota e retornado a lista passaria, mas não é o que aconteceu.
Analisando o teste ele faz um post de um tarefa. na linha 17 do aquivo de teste.

```js
    // todos.spec 
    const todoResponse = await request(app)
      .post('/todos')
      .send({
        title: 'test todo',
        deadline: todoDate
      })
      .set('username', userResponse.body.username)
```
Por isso só criando a GET /todos o teste não passa, ele quebra porque a rota POST /todos não foi implementada .
Minha sugestão caso meu argumento não esteja equivocado é que o teste faça um requisição GET e verifique se o retorno e uma array.

Exemplo:
```js
  it("should be able to list all user's todo", async () => {
    const userResponse = await request(app)
      .post('/users')
      .send({
        name: 'John Doe',
        username: 'user1'
      });

    const todoResponse = await request(app)
      .get('/todos')
      .set('username', userResponse.body.username);

    expect(todoResponse.body).toEqual([])

  });
  ```

**Comment by danilo-vieira** [comment]
Opa @rogeriop1990cv tudo bem?
Para que esse teste passe, é importante que a rota POST esteja implementada antes. Isso porque o servidor está salvando os _todos_ dos usuários em memória, assim sendo, caso a rota GET seja chamada sem que nenhum _todo_ tenha sido cadastrado naquele momento, a resposta será vazia e seria impossível validar o teste dessa maneira.

É por esse mesmo motivo, inclusive, que além dos _todos_, um novo usuário também é cadastrado no momento em que o teste é executado:
```
const userResponse = await request(app)
  .post('/users')
  .send({
    name: 'John Doe',
    username: 'user1'
  });
```
